feat(eip): control whether use EIP when creating ECS
huaweicloud/packer-plugin-huaweicloud pull request #108
Opened 2024-05-14 11:36 UTC by Zippo-Wang

2024-05-22 02:36 UTC, chengxiangdong requested changes
请根据检视建议调整一下

2024-05-22 02:36 UTC, chengxiangdong commented on builder/ecs/run_config.go
> +
这里好像有bug，原本控制是不使用EIP时就不创建EIP，但是如果使用EIP的话，自动创建的EIP也不能绑定到ECS了

2024-05-22 02:36 UTC, chengxiangdong commented on builder/ecs/run_config.go
> +	AssociatePublicIpAddress string `mapstructure:"associate_public_ip_address" required:"false"`
试试使用`*bool`类型，即不指定这个参数时默认为分配一个EIP

2024-05-22 02:36 UTC, chengxiangdong commented on example/deny_eip/image_with_deny_eip.pkr.hcl
> +  associate_public_ip_address = "false"
用例完善一下，把vpc_id、subnet_id补充上。

2024-05-22 02:36 UTC, chengxiangdong commented on example/deny_eip/image_with_deny_eip.pkr.hcl
建议文件夹、文件名改为：private_ip，image_with_private_ip.prk.hcl

2024-05-22 02:39 UTC, chengxiangdong commented
建议在wiki中也补充上使用private IP构建镜像的例子

2024-05-23 03:01 UTC, chengxiangdong commented
Please add the following description under the new example:

> NOTE:
> In the template, you need to provide the VPC ID, subnet ID, and security group ID.
> Please ensure that the network of the server executing Packer is interconnected with them.

2024-05-23 03:01 UTC, chengxiangdong reviewed
请重新整改一下

2024-05-23 06:30 UTC, Zippo-Wang commented on docs-partials/builder/ecs/RunConfig-not-required.mdx
> +- `associate_public_ip_address` (\*bool) - Whether or not allow to create EIP, default to true
> [!Note]
> ok

2024-05-23 06:46 UTC, chengxiangdong commented on example/private_ip/image_with_private_ip.pkr.hcl
> +  # 3. `security_groups`;
这段描述不对，在样例中没必要将参数的使用描述这么详细，建议去掉。

2024-05-23 06:46 UTC, chengxiangdong commented on example/private_ip/variables.pkr.hcl
> +}
文件末尾添加一个空行吧，老惯例了....

2024-05-23 06:46 UTC, chengxiangdong commented on example/private_ip/variables.pkr.hcl
> +  default = "ap-southeast-1"
默认值可能会带来误导，去掉吧

2024-05-23 07:38 UTC, chengxiangdong commented
LGTM

2024-05-23 07:38 UTC, merged